### ISSUE TITLE
VCF2MAF python Tool

### ISSUE THREAD

**Issue by rmadupuri** [knowledgesystems/curation-scrum#1476]
- [x] Explore GENIE Annotation suite. Can the code be used for other purposes? Like to create a sharable standalone tool to go from vcf to maf. Explore the command line.
- [ ] Create a README for the VCF2MAF tool.
- [ ] Explore `click` package for command line interface. Add an additional command line argument to take in the list of files (comma separated).
- [ ] Parallelize the runs for each file. Maybe use a bash script with a for loop.
- [ ] Add the VCF2MAF tab on the Genome Nexus page.
- [ ] Maybe create a Genome Nexus Annotation package with different tools that people can download and install
